### Registro de usuário
POST http://localhost:3009/register
Content-Type: application/json

{
    "usuario": "d",
    "password": "d",
    "descricao": "usuario teste4"
}

### Login do usuário
POST http://localhost:3009/login
Content-Type: application/json

{
    "usuario": "d",
    "password": "d"
}