### Obter token JWT
POST http://localhost:3009/login
Content-Type: application/json

{
    "usuario": "b",
    "password": "b"
}

### Criar categoria
POST http://localhost:3009/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6ImIiLCJpYXQiOjE3MjAwMzY1NjksImV4cCI6MTcyMDA0MDE2OX0.mohOqnN0u89R15Bk6lFY2yk_K4RgubluRrPkztou-D8

{
    "nome": "Eletronicos",
    "descricao": "Itens eletronicos variados"
}

### Obter todas as categorias
GET http://localhost:3009/categorias
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6ImIiLCJpYXQiOjE3MjA0NzIyNzYsImV4cCI6MTcyMDQ3NTg3Nn0.EmMMjAyioZpALfEDKTaf6CHiyjLxCopiM66s7fgqN4Q

### Obter categoria por ID
GET http://localhost:3009/categorias/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6ImIiLCJpYXQiOjE3MjAwMzY1NjksImV4cCI6MTcyMDA0MDE2OX0.mohOqnN0u89R15Bk6lFY2yk_K4RgubluRrPkztou-D8

### Atualizar Categoria