POST http://localhost:3009/itens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6ImIiLCJpYXQiOjE3MjA0NzM2MDEsImV4cCI6MTcyMDQ3NzIwMX0.Pb2aBnyH8I_dvPKW1VveQYkJ0SWRMVaeOuJ-QfHsFhg

{
    "nome": "Moto Eletrica",
    "id_categoria": 1, 
    "descricao": "Motinho azul",
    "status": "disponivel"
}

### Obter todos os itens
GET http://localhost:3009/itens
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6ImIiLCJpYXQiOjE3MjA0NzM3ODcsImV4cCI6MTcyMDQ3NzM4N30.e1_xx-X2JEtzFiS3_5lBsIAdq1fXCKybH7LXGWvCXWI

### 