POST http://localhost:3009/itens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6ImIiLCJpYXQiOjE3MjA1MzQ3NjksImV4cCI6MTcyMDUzODM2OX0.m-TUQry6uVenjp9kf2cgAq14ISSxjKBLGG2cdkQtjUg

{
    "nome": "Moto Eletrica",
    "id_categoria": 1, 
    "descricao": "Motinho azul",
    "status": "disponivel"
}

### Obter todos os itens
GET http://localhost:3009/itens
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6ImIiLCJpYXQiOjE3MjA1MzQ3NjksImV4cCI6MTcyMDUzODM2OX0.m-TUQry6uVenjp9kf2cgAq14ISSxjKBLGG2cdkQtjUg

### 